print("\'Hello, World!.\'")
print("Muhammad Uzair")
print("Muhammad Uzair " + "Yasin" )
print(123)
print("Hello\nWorld")
print("Hello\tWorld")
print("Apple" , "banana" , "cherry", sep=",")
print(1,2,3, sep="-")
print("Hello" , end=" ")
print("World")
print(1 , end="")
print(2)
print("He said, \"Hello!.\" ")
print("This is Blackslash : \\")
print("I am " + str(20) + " years old")
print("The number is " + str(5))
for x in range(1,6):
    print(x)

print("Amir Bahi , Uziar ")    